services:
  - type: web
    name: health-chatbot-final
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn --workers 4 --worker-tmp-dir /dev/shm --timeout 600 app:app"
    healthCheckPath: /health
    envVars:
      - key: GOOGLE_API_KEY
        sync: false